apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name}}-app
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        env: {{ .Values.env }}
    spec:
      containers:
      - name: {{ .Values.app.name}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.container.port }}

        readinessProbe:
          httpGet:
            path: "/actuator/health"
            port: {{ .Values.container.port }}
          initialDelaySeconds: 20

        livenessprobe:
          httpGet:
            path: "/actuator/health"
            port: {{ .Values.container.port }}
          initialDelaySeconds: 20
    