apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.service.name }}
    labels:
        app: {{ .Values.app.name }}
        env: {{ .Values.env }}
spec:
    type: ClusterIP
    selector:
            app: {{ .Values.app.name }}
            env: {{ .Values.env }}
    ports:
        - name: http
          port: {{ .Values.service.port }}
          targetPort: {{ .Values.container.port }}