app:
  name: petclinic

replicas: 2

env: dev

image:
  repository: naraharinitheesh/petclinic
  tag: 10

container:
  port: 8080

service:
  name: petclinic-svc
  port: 8080

ingress:
  name: petclinic-ingress
  path: /
