app:
  name: petclinic
namespace: petclinic
replicas: 2

env: dev

image:
  repository: naraharinitheesh/petclinic
  tag: 8

container:
  port: 8080

service:
  name: petclinic-svc
  port: 8080

ingress:
  enabled: true
  name: petclinic-ingress
  path: /
